version: '3.7'

services:
  # proxy:
  #   image: nginx:alpine
  #   container_name: proxy
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend

  api:
    container_name: api
    build:
      context: .
      target: development-build-stage
      dockerfile: ./docker/api/Dockerfile
    ports:
      - '4000:3000'
    volumes:
      - ./api:/app
      # - /app/node_modules
    restart: 'unless-stopped'
    depends_on:
      - database
      - cache
    command: sh -c "./start.sh && npm run dev"
    networks:
      - cv-backend

  database:
    container_name: database
    image: mysql:8.0.32
    restart: unless-stopped
    # restart: always
    # depends_on: 
    #   - db
    volumes:
      - cv-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      # MYSQL_USER: mysql
      # MYSQL_PASSWORD: root
      # MYSQL_DATABASE: cv
    networks:
      - cv-backend
      
  cache:
    container_name: redis-cache
    image: redis:7.0.9-alpine3.17
    restart: unless-stopped
    volumes:
      - cv-cache:/data
    ports:
      - '6379:6379'
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    networks:
      - cv-backend


networks:
  cv-backend:
    driver: bridge

volumes:
  cv-cache:
    driver: local
  cv-data:
    driver: local