version: '3.7'

services:
  # proxy:
  #   image: nginx:alpine
  #   container_name: proxy
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend

  api:
    container_name: api
    build:
      context: .
      target: development-build-stage
      dockerfile: ./docker/api/Dockerfile
    ports:
      - '4000:3000'
    volumes:
      - ./api:/app
      # - /app/node_modules
    restart: 'unless-stopped'
    command: sh -c "./start.sh && npm run dev"
    networks:
      - backend

  database:
    container_name: database
    image: mysql:8.0.32
    restart: unless-stopped
    # restart: always
    depends_on: 
      - db
    volumes:
      - cv-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: mysql
      # MYSQL_PASSWORD: root
      # MYSQL_DATABASE: cv
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  cv-data:
    driver: local
  # data:
  #   driver: local