export const { 
    NODE_ENV,
    PORT,
    ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET,
    CLIENT_ACCESS_TOKEN_SECRET,
    CLIENT_REFRESH_TOKEN_SECRET,
    ENCRYPTION_ALGORITHM,
    SALT_KEY,
    PASSWORD_KEY,
    APP_URL,
    CLIENT_ID,
    CLIENT_SECRET
} = process.env